version: '2'

services:

  db:
    container_name: pg
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: electroexpress
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: fake@mail.io
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "80:80"

volumes:
  db-data:
