from ecommerce.serializers.DesiredSerializer import DesiredSerializer
from ecommerce.serializers.InvoiceSerializer import InvoiceSerializer
from ecommerce.serializers.InvoiceSerializer import LineSerializer
from ecommerce.serializers.ProductSerializer import ProductSerializer
from ecommerce.serializers.PromoSerializer import PromoSerializer
